// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2025 Harald Sitter <sitter@kde.org>

package main

import (
	"fmt"
	"io"
	"log"
	"net/url"
	"os"

	"github.com/coreos/go-systemd/unit"
)

func main() {
	origFile := "/usr/lib/sysupdate.d/50-root-x86-64-erofs.transfer"
	if _, err := os.Stat(origFile); err != nil {
		log.Fatalln(err)
	}

	file, err := os.Open(origFile)
	if err != nil {
		log.Fatalln(err)
	}
	defer file.Close()

	options, err := unit.Deserialize(file)
	if err != nil {
		log.Fatalln(err)
	}

	var path *url.URL = nil
	for _, option := range options {
		if option.Section == "Source" && option.Name == "Path" {
			path, err = url.Parse(option.Value)
			if err != nil {
				log.Fatalln("Failed to parse path:", err)
			}
			break
		}
	}
	if path == nil {
		log.Fatalln("No Source Path found in", origFile)
	}

	fmt.Println("Original Source Path:", path)
	newPath := "http://localhost:3129" + path.Path
	fmt.Println("New Source Path:", newPath)

	newOption := unit.NewUnitOption("Source", "Path", newPath)

	overrideDir := "/run/sysupdate.d/50-root-x86-64-erofs.transfer.d"
	os.MkdirAll(overrideDir, 0755)

	outFile, err := os.Create(overrideDir + "/00-default.conf")
	if err != nil {
		log.Fatalln("Failed to create override file:", err)
	}
	defer outFile.Close()

	outFile.Write([]byte("# This file was automatically generated by kde-linux-sysupdated-redirector\n"))
	_, err = io.Copy(outFile, unit.Serialize([]*unit.UnitOption{newOption}))
	if err != nil {
		log.Fatalln("Failed to write override file:", err)
	}
	fmt.Println("Override file created at", outFile.Name())
}
