# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml

stages:
  - validate
  - build

golang-latest:
  stage: build
  image: golang:latest
  script:
    - make
